# config.yaml

database:
  host: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASS}
  name: ${POSTGRES_DB}

api:
  port: ${API_PORT}

auth:
  jwt_secret: ${JWT_SECRET}
  google:
    client_id: ${GOOGLE_CLIENT_ID}
    client_secret: ${GOOGLE_CLIENT_SECRET}
    callback_url: "http://localhost:8080/api/v1/auth/google/callback"
    scopes:
      - "https://www.googleapis.com/auth/userinfo.profile"
      - "https://www.googleapis.com/auth/userinfo.email"
      - "https://www.googleapis.com/auth/spreadsheets"

crypto:
  aes_key: ${AES_KEY}

kafka:
  broker: ${KAFKA_BROKER}
  synk_topic: synk_topic
  synk_group: synk_group
  write_topic: write_topic
  write_group: write_group

